###
GET http://localhost:8081/products

###
GET http://localhost:8081/products/5

###
POST http://localhost:8081/products
Content-Type: application/json

{
  "name": "New Product",
  "price": 100.125
}

###
GET http://localhost:8081/products/6

###
PATCH http://localhost:8081/products/6
Content-Type: application/json

{
  "name": "New Product New Name"
}

###
GET http://localhost:8081/products/6

###
PATCH http://localhost:8081/products/6
Content-Type: application/json

{
  "price": 99.954
}

###
GET http://localhost:8081/products/6

###
PATCH http://localhost:8081/products/6
Content-Type: application/json

{
  "name": "Old Product",
  "price": 0.01
}

###
GET http://localhost:8081/products/6

###
DELETE http://localhost:8081/products/6
